
setup:
	apt-get update
	apt-get install gcc
	apt-get install python3

run-hw0-stdio: 
	gcc c_stdio.c
	./a.out
	
run-hw0-alphabet:
	python3 alphabet.py

run-hw0-powerset:
	python3 powerset.py

run-hw0-xml:
	python3 xml.py